services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      POSTGRES_DSN: postgresql://myuser:mypassword@db:5432/mydb
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://server:8000
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
