name: Server Linter

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                python-version: "3.13"
                cache: "pip"
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install -r requirements_dev.txt
            
            - name: Check formatting
              run: |
                    black server/ --check
                
            - name: Run Linter
              run: |
                    pylint --fail-under=9.5 server/
                
            - name: Type check
              run: |
                    mypy server/
