name: Web Linter

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./web
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                version: 9

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run ESLint
              run: pnpm lint

            - name: Run Prettier check
              run: pnpm format --check

            - name: TypeScript type check
              run: pnpm check-types